### ISSUE TITLE
CR:  Create seed for Demo Database

### ISSUE THREAD

**Issue by KelseyDH** [pathwaysmedical/frasernw#228]
May just do with the database manually as it may be too difficult to do this from just a seed file.

**Comment by KelseyDH** [comment]
Some scrubbing / mixing still left to do:

- [ ] Hospital/Clinic Specialist Privileges/Attendance ids

- [ ] Date fields in various places, e.g. `unavailable_to`, `unavailable_from` and `created_at` / `updated_at` fields.

- [ ] Boolean fields in various places revealing info, especially on Specialist/Clinic.
```
  referral_fax: true
  referral_phone: true
  respond_by_fax: false
  respond_by_phone: true
  respond_by_mail: false
  respond_to_patient: false
  urgent_fax: false
  urgent_phone: true
```
I'm thinking for this we can just randomize the boolean (though it may break things in a few places where a boolean leads to other defined behaviour).

- [ ] Integer fields storing type_hash mask integers such as `sex`, `waittime_mask`, `lagtime_mask`, `categorization_mask`

**Comment by bgracie** [comment]
- [ ] for each specialization, randomize the clinics and specialists attached to it, holding constant their respective numbers
- [ ] for each prodecure specialization, randomize the clinics and specialists attached to it, holding constant their respective numbers (must be consistent with the new specializations)

**Comment by bgracie** [comment]
- [ ] :the names  could be improved (we don’t need middle names)
- [ ] : the links to the Newsletter could be left in
- [ ] : some fake but readable Banners, Division Updates, Attachment updates, and Shared Care updates should be shown
- [ ] : a variety of latest specialist and clinic updates could be created.

**Comment by bgracie** [comment]
- [ ] more specialists should be green checks

**Comment by bgracie** [comment]
- [ ] Consider using the two comments that are presently displayed under the latest newsletter rather than the unreadable language;
Spotlight on Physician Resources
Fine Tuning your Geographic Search

- [ ] Keep the PSP Division Updates

- [ ] Under Attachment Updates, keep only the shorter update on 'Measuring a GP for Me Success’ and omit the first one to shorten the length of the middle column.  Decreasing the number of Latest Specialist and Clinic Updates will also shorten this column length.

- [ ] We should remove the admin access from the black menu bar and show only a user version.
--> depends on what login we give them

- [ ] Make sure that the ‘You’ tabs display but do not work for items in the ‘settings' section
--> code change

- [ ]  show more green arrow specialists under each specialty, and perhaps limit the blue arrow specialists to 2 to 5 for each specialty.
