### ISSUE TITLE
Upgrade to Rails 4.0

### ISSUE THREAD

**Issue by KelseyDH** [pathwaysmedical/frasernw#234]
Problem gems:

ancestry 1.3.0 depends on ActiveRecord ~2  (ancestry in higher versions breaks)

papertrail 2.7 depends on ActiveRecord 3

paperclip 2.7 depends on 2.3

------------
TODO:

- [x] Fix routes  — Doublecheck

- [x] fix rake broken_links references to deprecated Action::Caching::Fragments, require new one in

- [x] update SECRET_TOKEN to secret_key

- [x] Fix user.rb validates password regex

- [x] fix jquery assets breaking

- [x] add gems to fix Rails 4 deprecations

**Comment by bgracie** [comment]
- changes to/removal of Rails methods
- what version do we need to upgrade paperclip, paper trail, ancestry to?
- what breaking changes are involved?

**Comment by dhMuse** [comment]
Method changes and similar core changes:
- [ ] mass-assignment protection deprecated in favour of strong params
   - [ ] **Rails 4.0 has removed `attr_accessible` and `attr_protected` feature in favor of Strong Parameters. You can use the [Protected Attributes gem](https://github.com/rails/protected_attributes) for a smooth upgrade path.**
   - [ ] If you are not using Protected Attributes, you can remove any options related to this gem such as `whitelist_attributes` or `mass_assignment_sanitizer` options.
- [ ] scopes must always use callables [see commit](https://github.com/rails/rails/commit/50cbc03d18c5984347965a94027879623fc44cce)
- [ ] routes
   - [ ] `match` can't be used anymore
   - [ ] you will need to make a change if you are using `form_for` to update a resource in conjunction with a custom route using the `PUT` HTTP method [see 5.1](http://edgeguides.rubyonrails.org/upgrading_ruby_on_rails.html#upgrading-from-rails-3-2-to-rails-4-0)
   - [ ] relatedly, `json_patch`
- [ ] Thread safe by default. Check that the gems you are using are threadsafe.
   - [ ] `config.threadsafe!` is deprecated in favor of `config.eager_load`
- [ ] Strings rendered in erb are escaped unless wrapped with `raw` or `html_safe` is called.
- [ ] `Rails::Plugin` has gone
- [ ] Active Support
   - [ ] Replace deprecated `memcache-client` gem with `dalli` in `ActiveSupport::Cache::MemCacheStore`
   - [ ] `Object#try` will now return `nil` instead of raise a `NoMethodError` if the receiving object does not implement the method, but you can still get the old behavior by using the new `Object#try!`.
   - [ ] `String#to_date` now raises `ArgumentError: invalid date` instead of `NoMethodError: undefined method 'div' for nil:NilClass` when given an invalid date. It is now the same as `Date.parse`, and it accepts more invalid dates [see 9](http://guides.rubyonrails.org/4_0_release_notes.html)
   - Deprecations
      - [ ] Deprecate `ActiveSupport::TestCase#pending` method
      - [ ] `ActiveSupport::Benchmarkable#silence` has been deprecated
      - [ ] `ActiveSupport::JSON::Variable` is deprecated
      - [ ] Deprecates the compatibility method `Module#local_constant_names`
      - [ ] `BufferedLogger` is deprecated.
      - [ ] Deprecate `assert_present` and `assert_blank` in favor of `assert object.blank?` and `assert object.present?`
   - [ ] Rails 4.0 removes the `j` alias for `ERB::Util#json_escape`
- [ ] `ActiveRecord`
   - [ ] Remove `IdentityMap`
   - [ ] Remove automatic execution of `EXPLAIN` queries. The option `active_record.auto_explain_threshold_in_seconds` is no longer used and should be removed.
   - Deprecations
      - [ ] `ActiveRecord::Fixtures` in favor of `ActiveRecord::FixtureSet`.
      - [ ] `ActiveRecord::TestCase` in favor of `ActiveSupport::TestCase`.
      - [ ] Old-style hash based finder API. This means that methods which previously accepted "finder options" no longer do.
      - [ ] All dynamic methods except for `find_by_...` and `find_by_...!` are deprecated [see 11.2](http://guides.rubyonrails.org/4_0_release_notes.html)
         - [ ] To re-enable the old finders, you can use the `activerecord-deprecated_finders` gem.
         - [ ] `find_all_by_...` can be rewritten using `where(...)`.
         - [ ] `find_last_by_...` can be rewritten using `where(...).last`.
         - [ ] `scoped_by_...` can be rewritten using `where(...)`.
         - [ ] `find_or_initialize_by_...` can be rewritten using `find_or_initialize_by(...)`.
         - [ ] `find_or_create_by_...` can be rewritten using `find_or_create_by(...)`.
         - [ ] `find_or_create_by_...!` can be rewritten using `find_or_create_by!(...)`.
         - [ ] **Note that `where(...)` returns a relation, not an array like the old finders. If you require an Array, use `where(...).to_a`.**
   - [ ] In Rails 3 you could use `Model.scoped` to return Rails’s relation of all Model’s objects. In Rails 4 `.all` returns Rails Relation by default
   - [ ] When a column or a table is renamed the related indexes are also renamed. If you have migrations which rename the indexes, they are no longer needed.
   - [ ] Changed `serialized_attributes` and `attr_readonly` to class methods only. You shouldn't use instance methods since it's now deprecated. You should change them to use class methods, e.g. `self.serialized_attributes` to `self.class.serialized_attributes`.
   - [ ] When using the default coder, assigning `nil` to a serialized attribute will save it to the database as `NULL` instead of passing the `nil` value through `YAML ("--- \n...\n")`.
   - [ ] Rails 4.0 has changed to default join table for `has_and_belongs_to_many` relations to strip the common prefix off the second table name. Any existing `has_and_belongs_to_many` relationship between models with a common prefix must be specified with the `join_table` option. [see 5.4](http://edgeguides.rubyonrails.org/upgrading_ruby_on_rails.html#upgrading-from-rails-3-2-to-rails-4-0)
      - [ ] Note that the prefix takes scopes into account as well, so relations between `Catalog::Category` and `Catalog::Product` or `Catalog::Category` and `CatalogProduct` need to be updated similarly.
- [ ] `ActiveModel`
   - [ ] Changed how errors attach with the `ActiveModel::Validations::ConfirmationValidator`. Now when confirmation validations fail, the error will be attached to `:#{attribute}_confirmation` instead of `attribute`.
   - [ ] Changed `ActiveModel::Serializers::JSON.include_root_in_json` default value to `false`. [See 5.6](http://edgeguides.rubyonrails.org/upgrading_ruby_on_rails.html#upgrading-from-rails-3-2-to-rails-4-0)
- [ ] `ActiveRecord::Observer` and `ActionController::Caching::Sweeper` have been extracted to the `rails-observers` gem
- [ ] ActionPack
   - [ ] [See 5.7 long note on `ActiveSupport::KeyGenerator` regarding setting `secret_key_base`](http://edgeguides.rubyonrails.org/upgrading_ruby_on_rails.html#upgrading-from-rails-3-2-to-rails-4-0)
   - [ ] Removed the `ActionController::Base.asset_path` option. Use the assets pipeline.
   - [ ] Removed Action and Page caching from Action Pack. You will need to add the `actionpack-action_caching` gem in order to use `caches_action` and the `actionpack-page_caching` to use `caches_pages` in your controllers.
   - [ ] Removed the XML parameters parser. You will need to add the `actionpack-xml_parser` gem if you require this feature.
   - [ ] Changes the default layout lookup set using symbols or procs that return `nil`. To get the "no layout" behavior, return `false` instead of `nil`.
   - [ ] Changes the default `memcached` client from `memcache-client` to `dalli`. To upgrade, simply add gem '`dalli`' to your `Gemfile`.
   - [ ] Changed how `assert_generates`, `assert_recognizes`, and `assert_routing` work. Now all these assertions raise `Assertion` instead of `ActionController::RoutingError`.
   - [ ] Raises an `ArgumentError` if clashing named routes are defined. This can be triggered by explicitly defined named routes or by the resources method.
   - [ ] Changed the way unicode character routes are drawn. Now you can draw unicode character routes directly. If you already draw such routes, you must change them. [See 5.7, halfway down](http://edgeguides.rubyonrails.org/upgrading_ruby_on_rails.html#upgrading-from-rails-3-2-to-rails-4-0)
   - [ ] Removed `ActionDispatch::BestStandardsSupport` middleware, `<!DOCTYPE html>` already triggers standards mode per [standard](http://msdn.microsoft.com/en-us/library/jj676915(v=vs.85).aspx) and ChromeFrame header has been moved to `config.action_dispatch.default_headers`.
   - [ ] Precompiling assets no longer automatically copies non-JS/CSS assets from `vendor/assets` and `lib/assets`. Rails application and engine developers should put these assets in `app/assets` or configure `config.assets.precompile`.
   - [ ] `ActionController::UnknownFormat` is raised when the action doesn't handle the request format. By default, the exception is handled by responding with `406 Not Acceptable`, but you can override that now. In Rails 3, `406 Not Acceptable` was always returned. No overrides.
   - [ ] A generic `ActionDispatch::ParamsParser::ParseError` exception is raised when `ParamsParser` fails to parse request params. You will want to rescue this exception instead of the low-level `MultiJson::DecodeError`, for example.
   - [ ] `SCRIPT_NAME` is properly nested when engines are mounted on an app that's served from a URL prefix. You no longer have to set `default_url_options[:script_name]` to work around overwritten URL prefixes.
   - Deprecations
      - [ ] `ActionController::Base.page_cache_extension` option. Use `ActionController::Base.default_static_extension` instead.
      - [ ] `dom_id` and `dom_class` methods in controllers (they are fine in views). You will need to include the `ActionView::RecordIdentifier` module in controllers requiring this feature
      - [ ] `:confirm` option for the `link_to` helper. You should instead rely on a `data` attribute (e.g. `data: { confirm: 'Are you sure?' }`). This deprecation also concerns the helpers based on this one (such as `link_to_if` or `link_to_unless`).
      - [ ] `ActionController::Integration` in favor of `ActionDispatch::Integration`.
      - [ ] `ActionController::IntegrationTest` in favor of `ActionDispatch::IntegrationTest`.
      - [ ] `ActionController::PerformanceTest` in favor of `ActionDispatch::PerformanceTest`.
      - [ ] `ActionController::AbstractRequest` in favor of `ActionDispatch::Request`.
      - [ ] `ActionController::Request` in favor of `ActionDispatch::Request`.
      - [ ] `ActionController::AbstractResponse` in favor of `ActionDispatch::Response`.
      - [ ] `ActionController::Response` in favor of `ActionDispatch::Response`.
      - [ ] `ActionController::Routing` in favor of `ActionDispatch::Routing`.
- [ ] Do we rely on Helpers loading order? [see 5.9](http://edgeguides.rubyonrails.org/upgrading_ruby_on_rails.html#upgrading-from-rails-3-2-to-rails-4-0)

**Comment by dhMuse** [comment]
Useful resources:
* [Checklist](http://www.rails-upgrade-checklist.com/#4.0)
* [Edge guide](http://edgeguides.rubyonrails.org/upgrading_ruby_on_rails.html#upgrading-from-rails-3-2-to-rails-4-0)
* [RailsDiff](railsdiff.org/3.2.22/4.0.0) config differences comparison
* [Ready4Rails4?](http://www.ready4rails.net/) gem status list
* [Upgrading 3 to 4 on Heroku](https://devcenter.heroku.com/articles/rails4#upgrading-a-rails-3-app)

**Comment by dhMuse** [comment]
Checking current `Gemfile` gems against Ready4Rails4?
- [ ] gem 'nokogiri'
- [ ] gem 'pg'
- [ ] group :production do
  - [ ] gem 'heroku_cloud_backup',
    - [ ] git: "https://github.com/pathwaysmedical/heroku_cloud_backup.git",
    - [ ] ref: "8e801df1ad59515c3a89456169770b641d8c39a2"
- [ ] gem 'redis'
- [ ] group :assets do
  - [ ] gem 'sass', '~> 3.1.10'
  - [ ] gem 'sass-rails',   '~> 3.2.6'
  - [ ] gem 'coffee-rails', '~> 3.2.2'
  - [ ] gem 'uglifier',     '>= 1.0.3'
- [ ] gem 'connection_pool'
- [ ] gem 'highcharts-rails'
- [ ] gem 'jquery-rails', '~> 1.0.16'
- [ ] gem 'haml-rails', '~> 0.4'
- [ ] gem 'brakeman'
- [ ] gem 'authlogic'
- [ ] gem 'paper_trail', '~> 2.7'
- [ ] gem 'will_paginate', '~> 3.0.0'
- [ ] gem "simple_form", '~> 2.1'
- [ ] gem "nested_form", :git => "https://github.com/warneboldt/nested_form.git", :ref => "35a2cf060680280413880337a3f89bdec469301c"
- [ ] gem 'exception_notification'
- [ ] gem 'slack-notifier'
- [ ] gem 'cancan', '1.6.7'
- [ ] gem "paperclip", "~> 2.7"
- [ ] gem 'rack-attack'
- [ ] gem "aws-sdk", "< 2.0"
- [ ] gem 'public_activity'
- [ ] gem 'unicorn'
- [ ] gem 'edge_rider'
- [ ] gem 'kgio'
- [ ] gem 'dalli'
- [ ] gem 'rack-cache'
- [ ] gem 'delayed_job'
- [ ] gem 'delayed_job_active_record'
- [ ] gem 'delayed_job_web'
- [ ] gem 'daemons'
- [ ] gem 'clockwork'
- [ ] gem 'bluecloth'
- [ ] gem 'htmlentities'
- [ ] gem 'wannabe_bool', "~> 0.1.0" #get access to handy to_b boolean method
- [ ] gem 'valid_url' #parse urls for validity
- [ ] gem 'indefinite_article' # parse words for "a" or "an"
- [ ] gem 'hirefire-resource' # auto-scale heroku dynos based on demand
- [ ] gem 'hirb', :require => false
- [ ] gem 'awesome_print', :require => false
- [ ] gem 'bugsnag'
- [ ] gem 'virtus'
- [ ] group :test do
  - [ ] gem 'turn', :require => false
  - [ ] gem 'capybara'
  - [ ] gem 'selenium-webdriver'
- [ ] group :development, :test do
  - [ ] gem "nifty-generators"
  - [ ] gem 'rspec', '~> 3.2'
  - [ ] gem 'rspec-rails'
  - [ ] gem 'spork', '> 0.9.0rc'
  - [ ] gem 'guard'
  - [ ] gem 'guard-rspec'
  - [ ] gem 'guard-livereload'
  - [ ] gem 'guard-spork'
  - [ ] gem 'rack-livereload'
  - [ ] gem 'activerecord-import'
  - [ ] gem 'taps'
  - [ ] gem 'rb-fsevent', '~> 0.9.1'
  - [ ] gem 'quiet_assets'
  - [ ] gem 'faker'
- [ ] group :development do
  - [ ] gem 'oink'
  - [ ] gem 'peek'
  - [ ] gem 'annotate', '~> 2.6.5' #inserts schema as a comment into model code, to run~> annotate
  - [ ] gem 'letter_opener' # opens mail in browser
  - [ ] gem 'rails-erd' # makes graph of schema
  - [ ] gem 'bullet' #warns about N+1 queries
  - [ ] gem 'thin'
  - [ ] gem 'iron_fixture_extractor' # extract out data into fixtures
  - [ ] gem 'table_print' # print nice tables in IRB with tp command
  - [ ] gem 'quick_spreadsheet', '0.0.3',
    - [ ] git: "git@github.com:pathwaysmedical/quick_spreadsheet.git"
- [ ] gem 'pry-rails'
- [ ] group :development, :test do
  - [ ] gem 'pry-doc'
  - [ ] gem 'pry-nav'
  - [ ] gem 'pry-stack_explorer'
- [ ] gem 'ancestry', '~> 1.3.0' #ancestry breaks specialization.rb arrange methods in higher versions
- [ ] gem 'validates_email_format_of'
- [ ] gem "safety_mailer" # prevent emails getting sent in staging
- [ ] gem 'google-api-client', '0.7.1', require: "google/api_client"
- [ ] gem 'jquery-datatables-rails', '3.1.1'
- [ ] gem "rack-timeout"
- [ ] gem 'rails_12factor', group: :production
- [ ] gem 'test-unit', '~> 3.0'
- [ ] group :development, :production do
  - [ ] gem 'newrelic_rpm'

**Comment by dhMuse** [comment]
@bgracie A breaking change was introduced no later than [fcf5a45](https://github.com/pathwaysmedical/frasernw/commit/fcf5a45b7eb3ac0e15e525031e60616198166245).
It breaks the "last_visited" called in specialists/show.

**Comment by bgracie** [comment]
new strategy: let's both work off the `rail4` branch and check the checklist into the repo (https://github.com/pathwaysmedical/frasernw/blob/rails4/rails4_gem_upgrade.md)

**Comment by dhMuse** [comment]
@bgracie `rails4-daniel` is broken, so don't merge into `rails4`

**Comment by dhMuse** [comment]
TODO priorities in `rails4-daniel`:
- [ ] move assets and correctly config asset pipeline
- [ ] perhaps generate new `SECRET_TOKEN` for use with new `secret_key_base`

**Comment by bgracie** [comment]
I decided to hold off on upgrading to the new encrypted cookies (specifying `secret_key_base`) until we're sure we don't have to rollback, as suggested by the upgrade guide.

**Comment by bgracie** [comment]
N.B.  it looks like the Rails cache uses a slightly different serialization method in Rails4.  So, if you have memcached open with Rails 3 cached data, you will likely have to restart it when you switch to the Rails4 branch.  We'll also have wipe the cache on heroku's memcached when we deploy this.

**Comment by dhMuse** [comment]
Remove datatables? See 2a771fa43a9a8cce277ad57ec316c443c7899df6.
It's called only in `/views/reports/show`, and is the only jquery call in the whole app, I think.

**Comment by bgracie** [comment]
basic manual tests conducted

pages:

- [x] specialties#show
- [x] front#index
- [x] aop#show
- [x] specialist#show 
- [x] clinic#show
- [x] sc_categories#show

flows:

- [x] specialist
- [x] clinic

**Comment by bgracie** [comment]
TODO:

- [ ] fix errors in delayed mailers
  - [ ] arguments passed to url_for can't be handled. Please require routes or provide your own implementation
  - [ ] can't modify frozen NilClass

**Comment by bgracie** [comment]
TODO still:

- [ ] deprecations
- [ ] set secret_key_base

**Comment by dhMuse** [comment]
Deprecations to address before 4.1 upgrade:
- [ ] convert mass-assignment protection to strong params; remove protected_attributes gem
- [x] Active Support
   - [x] Deprecate `ActiveSupport::TestCase#pending` method
   - [x] `ActiveSupport::Benchmarkable#silence` has been deprecated
   - [x] `ActiveSupport::JSON::Variable` is deprecated
   - [x] Deprecates the compatibility method `Module#local_constant_names`
   - [x] `BufferedLogger` is deprecated.
   - [x] Deprecate `assert_present` and `assert_blank` in favor of `assert object.blank?` and `assert object.present?`
- [ ] `ActiveRecord`
   - [x] `ActiveRecord::Fixtures` in favor of `ActiveRecord::FixtureSet`.
   - [x] `ActiveRecord::TestCase` in favor of `ActiveSupport::TestCase`.
   - [ ] Old-style hash based finder API. This means that methods which previously accepted "finder options" no longer do.
   - [ ] All dynamic methods except for `find_by_...` and `find_by_...!` are deprecated [see 11.2](http://guides.rubyonrails.org/4_0_release_notes.html)
      - [x] To re-enable the old finders, you can use the `activerecord-deprecated_finders` gem. **nah**
      - [ ] `find_all_by_...` can be rewritten using `where(...)`.
      - [ ] `find_last_by_...` can be rewritten using `where(...).last`.
      - [ ] `scoped_by_...` can be rewritten using `where(...)`.
      - [ ] `find_or_initialize_by_...` can be rewritten using `find_or_initialize_by(...)`.
      - [ ] `find_or_create_by_...` can be rewritten using `find_or_create_by(...)`.
      - [ ] `find_or_create_by_...!` can be rewritten using `find_or_create_by!(...)`.
      - [ ] **Note that `where(...)` returns a relation, not an array like the old finders. If you require an Array, use `where(...).to_a`.**
- [x] ActionPack
   - [x] `ActionController::Base.page_cache_extension` option. Use `ActionController::Base.default_static_extension` instead.
   - [x] `dom_id` and `dom_class` methods in controllers (they are fine in views). You will need to include the `ActionView::RecordIdentifier` module in controllers requiring this feature
   - [x] `:confirm` option for the `link_to` helper. You should instead rely on a `data` attribute (e.g. `data: { confirm: 'Are you sure?' }`). This deprecation also concerns the helpers based on this one (such as `link_to_if` or `link_to_unless`).
   - [x] `ActionController::Integration` in favor of `ActionDispatch::Integration`.
   - [x] `ActionController::IntegrationTest` in favor of `ActionDispatch::IntegrationTest`.
   - [x] `ActionController::PerformanceTest` in favor of `ActionDispatch::PerformanceTest`.
   - [x] `ActionController::AbstractRequest` in favor of `ActionDispatch::Request`.
   - [x] `ActionController::Request` in favor of `ActionDispatch::Request`.
   - [x] `ActionController::AbstractResponse` in favor of `ActionDispatch::Response`.
   - [x] `ActionController::Response` in favor of `ActionDispatch::Response`.
   - [x] `ActionController::Routing` in favor of `ActionDispatch::Routing`.
- [ ] write all the tests :-/

**Comment by dhMuse** [comment]
Maybe we should consider taking [the advice in this article](https://edelpero.svbtle.com/strong-parameters-the-right-way) into account when implementing strong params.

**Comment by dhMuse** [comment]
Closed in favour of CR#27.
