### ISSUE TITLE
search does not show "eye cancer - oncology"

### ISSUE THREAD

**Issue by bgracie** [pathwaysmedical/frasernw#249]

**Comment by KelseyDH** [comment]
I suspect it's due to the lack of space when the name gets created.  In search the Area of Practice / Procedure is getting generated as **Pediatric opthalmology (surgical/procedural)/eye cancer - oncology**  (see attached photo)

I think the lack of a space between *(surgical procedure)* and *eye cancer* is what's making it hard for the fuzzy search to match `pediatric eye` to this AOP.

 
<img width="1318" alt="screen shot 2015-12-03 at 5 35 44 pm" src="https://cloud.githubusercontent.com/assets/6710303/11578620/57ba7b8a-99e4-11e5-9d9b-fdb6dde424b5.png">
